//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_Final_version3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Enrollment
    {
        [Required]
        public int EnrollmentId { get; set; }

        [Required]
        public string Grade { get; set; }

        [Required]
        public Nullable<int> CourseId { get; set; }

        [Required]
        public Nullable<int> StudentId { get; set; }


        [Required]
        public virtual Course Course { get; set; }

        [Required]
        public virtual Student Student { get; set; }
    }
}
